# Generated by Django 4.0.3 on 2022-12-17 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0021_alter_category_name_alter_post_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 2, 28, 33, 806058)),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.category', verbose_name='This is the help text'),
        ),
    ]
